### ISSUE TITLE
Lokal utvecklingsmiljö

### ISSUE THREAD

**Issue by simpel** [RegionHalland/halland-design#1]
# User story
Som utvecklare vill jag ha en lokal utvecklingsmiljö så att jag kan utveckla ny funktionalitet utan att förstöra för andra

# Acceptanskriterier
- [x] Miljön är uppsatt lokalt och det går att se något i browsern
- [x] Miljön har en basinstallation av vår WP setup, dvs. med vårt huvudtema m.m.
- [x] Stegen som krävs för att få igång miljön är dokumenterade i readme filen till det repos som är kopplat till miljön. (Tänk på att reposet ligger publikt så inga lösenord eller känslig information)
- [ ] Önskvärt AC:  en staging server är kopplat till miljön och det är dokumenterat hur man pushar till den.

**Comment by viktor-sarge** [comment]
Manual för installation är under redigering och finns på readme:n. Behöver stämma av en del med David ang. de finare detaljerna och vissa steg jag inte är säker på. Kvar också att beskriva relationen mellan halland-repot och detta.

**Comment by simpel** [comment]
Härligt!

**Comment by viktor-sarge** [comment]
Lägger den här för granskning. Du får hojta Joel om hur du ev. vill trimma Readme:n.
