### ISSUE TITLE
Static pages

### ISSUE THREAD

**Issue by simpel** [RegionHalland/halland-design#3]
# User story
Som besökare vill jag kunna ta del av sidor med information så att jag kan förkovra mig

# Acceptanskriterier

## Generella AC:s
- [ ] Det går att ta del av sidorna på  stageing servern för design.regionhalland.se
- [x] En bastypografi är satt som inkluderar 
   - [x] p
   - [x] listor, båda punkt och numrerade, 
   - [x] h1-h6
   - [x] möjligheten att sätta en ingress
   - [x] Placering av bilder
- [x] Varje sida har en URL-friendly URL
- [x] Varje sida går bra att skriva ut
- [x] Det går att se när sidan publicerades
- [x] Det går att se när sidan uppdaterades
- [x] Det går att se vem som är ansvarig för informationen på sidan

## AC:s kopplat till redaktören

- [x] Som redaktör kan jag ange vart i sidstrukturen som sidan skall ligga
- [x] Som redaktör kan jag ange ett publiceringsdatum för sidan
- [x] Som redaktör kan jag ange en sidtitel för sidan
- [x] Som redaktör kan jag ange ett URL-namn för sidan

## Standard AC:s
- [x] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by viktor-sarge** [comment]
Alla redaktörskriterierna löser vi med default WP.

**Comment by viktor-sarge** [comment]
Att på sidan visa när en sida publicerats, uppdaterats och vem som är ansvarig ligger i sidfoten så jag tolkar det som att man skall kunna göra det i backend. Det löses i så fall med default WP-funktionalitet. Släcker därför dessa AC:s

**Comment by viktor-sarge** [comment]
Vi släcker punkterna om bastypografi osv då David redan byggt en article-komponent.
