### ISSUE TITLE
Sidhuvud

### ISSUE THREAD

**Issue by simpel** [RegionHalland/halland-design#4]
# User story
Som besökare vill jag kunna navigera i en huvudmeny så att jag kan förstå sidan upplägg och hitta det jag söker

# Acceptanskriterier

- [x] Det går att tabba sig igenom de olika valen i huvudmenyn
- [x] Länkarna i menyn kan hänvisa till en sida i WP, ett blogginlägg eller en extern URL
- [x] Det går att förstå vilken sida jag just nu besöker
- [x] Det går att förstå vilken avdelning jag just nu besöker
- [x] Som redaktör kan jag ange namnet/labeln på alla länkar
- [ ] Som redaktör kan jag ange om sidhuvudet skall ha en sökfunktion eller inte
- [ ] Som redaktör kan jag ange om sidhuvudet skall ha en logga in länk eller inte
- [ ] Som redaktör kan jag ange om sidhuvudet skall ha en byt språk länk eller inte
- [ ] Som redaktör kan jag ange om sitename skall synas eller inte
- [x] Som besökare kan jag klicka på menyikonen i mobilen och se menyn fällas ut

## Standard AC:s
- [x] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

- Flyout menyn ingår ej i storyn
- Beteendet för söket ingår ej i storyn

Designskisser finns här: https://invis.io/7XFQHU695C3 
Storyn omfattar endast huvudmenyn, dvs. den "raden" som har logotypen på sig.. :)

**Comment by viktor-sarge** [comment]
Arbetar för närvarande enligt hypotesen att Wordpress befintliga GUI för att skapa navigation kan användas och att temat i princip bara behöver sköta CSS:en. Stämmer av med David nästa v.

**Comment by simpel** [comment]
@regionhallandviktor När du skriver GUI så är det adminläget du syftar på va? Jag tänker att vi kör på det som finns, passar vår meny inte in riktigt på det så kanske vi kan ändra en del i hur menyn funkar på sajten... Så att vi inte hackar något eget som får framtida versioner av WP att krångla.

**Comment by viktor-sarge** [comment]
Nu är det byggt så nära standard som möjligt. Har tweakat header.blade.php i en ny fil, gjort lite CSS och och ändrat app.blade.php för att visa den nya filen för menyerna. Inser att momentet med t.ex. valbar sök, språkväljare osv kräver lite mer kunskap om backend i WP. Håller på och forskar i det hela.

**Comment by viktor-sarge** [comment]
(Insåg att vi måste arrangera om ordningen på elementen och prövar en flexbox-approach för att slippa scripta det. Ligger en tidig test i repot. Bygger funktionaliteten för menyn, men kommer behöva städa rätt mycket när jag o David hinner stämma av best practice-frågorna. Valbara komponenter är beroende av att David kollar upp hur man skapar ACF-fält direkt i PHP så kommer framöver)

**Comment by viktor-sarge** [comment]
- [x] CSS - snygga till. 
- [ ] CSS - BEM-granskning av David. 
- [x] Ändra blade-filen så mobil layout är default
- [x] Ändra CSS:en för att spegla ändringarna i blade-filen
- [x] Mobil nav - gör en grundlayout
- [x] Mobil nav - eget case för funktionaliteten kring subnivåer mm? 
- [x] Mobil nav - animera dölja/visa div. Var lägger vi skriptet - David. 
- [ ] Ikonerna - lägg in dem i sprite sheet istället m hjälp av David
- [x] Testa flexbox-design för att kunna arrangera om elementen
- [x] Mindre logga på tablet. Byt m CSS
- [x] Grundlayout web HD
- [x] Grundlayout web
- [x] Grundlayout tablet
- [x] Grundlayout mobil

**Comment by viktor-sarge** [comment]
Satte David som asignee här. Snyggt jobbat! 

Upptäckte några saker: 
* Menynamnet är hårdkodat så PHP får spel om en meny med rätt namn saknas eftersom funktionen inte får en array som input. Kan vi kolla datatypen och mata ut ett klartextmeddelande till redktören istället? 
* Alt-text saknas på loggan. 
* Menyn verkar än så länge mata ut alla nivåer och inte bara nivå 1 - WIP?

**Comment by viktor-sarge** [comment]
Edit: De här kan vi prata om nästa v. Har kört sidan i skärmläsare och ser att det behövs en noggrannare spec på vad som behöver göras för att det skall funka bra.

Några till: 
* Alt-text på bild(er)
* länkar behöver funkar för skärmläsare
* buttons behöver funka för skärmläsare
